/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * django-allauth: Headless API
 * Allauth spec
 * OpenAPI spec version: 1
 */
import type { AuthenticatedResponse } from '../djangoAllauthHeadlessAPI.schemas';

import { customAxiosInstance } from '../../axios';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Retrieve information about the authentication status for the current
session.

 * @summary Get authentication status

 */
export const getAllauthClientV1AuthSession = (
  client: 'app' | 'browser',
  options?: SecondParameter<typeof customAxiosInstance>
) => {
  return customAxiosInstance<AuthenticatedResponse>(
    { url: `/_allauth/${client}/v1/auth/session`, method: 'GET' },
    options
  );
};
/**
 * Logs out the user from the current session.

 * @summary Logout
 */
export const deleteAllauthClientV1AuthSession = (
  client: 'app' | 'browser',
  options?: SecondParameter<typeof customAxiosInstance>
) => {
  return customAxiosInstance<unknown>({ url: `/_allauth/${client}/v1/auth/session`, method: 'DELETE' }, options);
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type GetAllauthClientV1AuthSessionResult = NonNullable<
  Awaited<ReturnType<typeof getAllauthClientV1AuthSession>>
>;
export type DeleteAllauthClientV1AuthSessionResult = NonNullable<
  Awaited<ReturnType<typeof deleteAllauthClientV1AuthSession>>
>;
