# Generated by Django 5.1.8 on 2025-05-05 19:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='invitation', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('invitation_accepted', models.BooleanField(default=False)),
                ('invitation_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
