# Generated by Django 5.1.8 on 2025-08-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcowittObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stationtype', models.CharField(max_length=64)),
                ('runtime', models.BigIntegerField()),
                ('heap', models.BigIntegerField()),
                ('dateutc', models.DateTimeField()),
                ('tempinf', models.FloatField()),
                ('humidityin', models.IntegerField()),
                ('baromrelin', models.FloatField()),
                ('baromabsin', models.FloatField()),
                ('tempf', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('winddir', models.IntegerField()),
                ('windspeedmph', models.FloatField()),
                ('windgustmph', models.FloatField()),
                ('maxdailygust', models.FloatField()),
                ('solarradiation', models.FloatField()),
                ('uv', models.IntegerField()),
                ('rainratein', models.FloatField()),
                ('eventrainin', models.FloatField()),
                ('hourlyrainin', models.FloatField()),
                ('dailyrainin', models.FloatField()),
                ('weeklyrainin', models.FloatField()),
                ('monthlyrainin', models.FloatField()),
                ('yearlyrainin', models.FloatField()),
                ('totalrainin', models.FloatField()),
                ('wh65batt', models.CharField(max_length=16)),
                ('freq', models.CharField(max_length=16)),
                ('model', models.CharField(max_length=64)),
                ('interval', models.IntegerField()),
            ],
            options={
                'ordering': ['-dateutc', '-created_at'],
            },
        ),
    ]
