# Generated by Django 5.1.8 on 2025-08-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecowitt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcowittObservation5Min',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bucket_start', models.DateTimeField(unique=True)),
                ('sample_count', models.IntegerField(default=0)),
                ('tempinf_avg', models.FloatField()),
                ('humidityin_avg', models.FloatField()),
                ('baromrelin_avg', models.FloatField()),
                ('baromabsin_avg', models.FloatField()),
                ('tempf_avg', models.FloatField()),
                ('humidity_avg', models.FloatField()),
                ('winddir_avg', models.FloatField()),
                ('windspeedmph_avg', models.FloatField()),
                ('windgustmph_max', models.FloatField()),
                ('maxdailygust_max', models.FloatField()),
                ('solarradiation_avg', models.FloatField()),
                ('uv_avg', models.FloatField()),
                ('rainratein_avg', models.FloatField()),
                ('eventrainin_last', models.FloatField()),
                ('hourlyrainin_last', models.FloatField()),
                ('dailyrainin_last', models.FloatField()),
                ('weeklyrainin_last', models.FloatField()),
                ('monthlyrainin_last', models.FloatField()),
                ('yearlyrainin_last', models.FloatField()),
                ('totalrainin_last', models.FloatField()),
            ],
            options={
                'ordering': ['-bucket_start', '-created_at'],
            },
        ),
    ]
