/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * django-allauth: Headless API
 * Allauth spec
 * OpenAPI spec version: 1
 */
import type { ProviderAccountBody, ProviderAccountsResponse } from '../djangoAllauthHeadlessAPI.schemas';

import { customAxiosInstance } from '../../axios';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary List the connected third-party provider accounts
 */
export const getAllauthClientV1AccountProviders = (
  client: 'app' | 'browser',
  options?: SecondParameter<typeof customAxiosInstance>
) => {
  return customAxiosInstance<ProviderAccountsResponse>(
    { url: `/_allauth/${client}/v1/account/providers`, method: 'GET' },
    options
  );
};
/**
 * Disconnect a third-party provider account, returning the remaining
accounts that are still connected. The disconnect is not allowed if it
would leave the account unusable. For example, if no password was
set up yet.

 * @summary Disconnect a third-party provider account

 */
export const deleteAllauthClientV1AccountProviders = (
  client: 'app' | 'browser',
  providerAccountBody: ProviderAccountBody,
  options?: SecondParameter<typeof customAxiosInstance>
) => {
  return customAxiosInstance<ProviderAccountsResponse>(
    {
      url: `/_allauth/${client}/v1/account/providers`,
      method: 'DELETE',
      headers: { 'Content-Type': 'application/json' },
      data: providerAccountBody,
    },
    options
  );
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type GetAllauthClientV1AccountProvidersResult = NonNullable<
  Awaited<ReturnType<typeof getAllauthClientV1AccountProviders>>
>;
export type DeleteAllauthClientV1AccountProvidersResult = NonNullable<
  Awaited<ReturnType<typeof deleteAllauthClientV1AccountProviders>>
>;
