/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * django-allauth: Headless API
 * Allauth spec
 * OpenAPI spec version: 1
 */
import type { EndSessionsBody, SessionsResponse } from '../djangoAllauthHeadlessAPI.schemas';

import { customAxiosInstance } from '../../axios';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary List sessions
 */
export const getAllauthClientV1AuthSessions = (
  client: 'app' | 'browser',
  options?: SecondParameter<typeof customAxiosInstance>
) => {
  return customAxiosInstance<SessionsResponse>({ url: `/_allauth/${client}/v1/auth/sessions`, method: 'GET' }, options);
};
/**
 * @summary End one or more sessions
 */
export const deleteAllauthClientV1AuthSessions = (
  client: 'app' | 'browser',
  endSessionsBody: EndSessionsBody,
  options?: SecondParameter<typeof customAxiosInstance>
) => {
  return customAxiosInstance<SessionsResponse>(
    {
      url: `/_allauth/${client}/v1/auth/sessions`,
      method: 'DELETE',
      headers: { 'Content-Type': 'application/json' },
      data: endSessionsBody,
    },
    options
  );
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type GetAllauthClientV1AuthSessionsResult = NonNullable<
  Awaited<ReturnType<typeof getAllauthClientV1AuthSessions>>
>;
export type DeleteAllauthClientV1AuthSessionsResult = NonNullable<
  Awaited<ReturnType<typeof deleteAllauthClientV1AuthSessions>>
>;
