name: Deploy Heaven Club Full Stack

on:
  # Trigger the workflow on matching numeric semver pushed tags, i.e., 1.0.0, 20.15.10
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Script environment variables
env:
  BE_DOCKER_IMAGE_NAME: heavenclub-be
  DOCKER_REGISTRY: dockerregistry.local.hlab.es

jobs:
  build-and-push-backend:
    name: Build and Push Backend
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get the tag name
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/docker/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.BE_DOCKER_IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.BE_DOCKER_IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.BE_DOCKER_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.BE_DOCKER_IMAGE_NAME }}:buildcache,mode=max

  deploy-backend:
    name: Deploy Backend
    needs: build-and-push-backend
    runs-on: self-hosted

    steps:
      - name: Trigger Watchtower
        run: |
          curl -H "Authorization: Bearer ${{ secrets.WATCHTOWER_API_TOKEN }}" ${{ secrets.WATCHTOWER_URL }}/v1/update -v 